# Generated by Django 2.0.2 on 2018-02-13 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='email_address',
            new_name='email',
        ),
    ]
