# Generated by Django 2.0.2 on 2018-02-13 10:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180213_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 2, 13, 16, 2, 51, 5974))),
                ('modified_on', models.DateTimeField(default=datetime.datetime(2018, 2, 13, 16, 2, 51, 6013))),
            ],
        ),
        migrations.DeleteModel(
            name='TimeStamps',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='id',
        ),
        migrations.AddField(
            model_name='myuser',
            name='basemodel_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.BaseModel'),
            preserve_default=False,
        ),
    ]
