# Generated by Django 2.0.2 on 2018-02-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180213_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='modified_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
