# Generated by Django 2.0.2 on 2018-02-14 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180214_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='email_token',
            field=models.CharField(default='hghgjhh', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='email_token_created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 14, 14, 39, 3, 608418)),
        ),
    ]
