# Generated by Django 2.0.2 on 2018-02-20 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180214_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email_token_created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 20, 14, 47, 20, 116922)),
        ),
    ]
