# Generated by Django 2.0.2 on 2018-02-23 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20180222_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email_token_created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 23, 14, 35, 20, 382868)),
        ),
    ]
