# Generated by Django 2.0.2 on 2018-02-23 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20180221_1616'),
        ('accounts', '0018_auto_20180223_1457'),
    ]

    operations = [
    ]
