# Generated by Django 2.0.2 on 2018-02-26 12:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20180223_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email_token_created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 26, 12, 38, 26, 668406, tzinfo=utc)),
        ),
    ]
