# Generated by Django 2.0.2 on 2018-02-28 10:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20180226_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email_token_created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 28, 10, 8, 42, 111891, tzinfo=utc)),
        ),
    ]
