# Generated by Django 2.0.2 on 2018-02-13 10:18

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isSubscription', models.BooleanField(default=False)),
                ('customer_order_id', models.BigIntegerField()),
                ('payment_type', models.CharField(choices=[('C', 'Cash on Delivery'), ('N', 'Net Banking'), ('U', 'UPI'), ('D', 'Debit/Credit Cards')], default='C', max_length=1)),
                ('payment_status', models.BooleanField(default=False)),
                ('shipping_status', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.CharField(max_length=1000)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('avail_quantity', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=5000)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('users_rated', models.IntegerField(default=0)),
                ('isCombo', models.BooleanField(default=False)),
                ('CategoryIDs', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('ComboProductIDs', models.ManyToManyField(to='products.Products')),
            ],
        ),
        migrations.AddField(
            model_name='cartproducts',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Products'),
        ),
        migrations.AddField(
            model_name='cartproducts',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
