# Generated by Django 2.0.2 on 2018-02-19 10:30

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_number', models.IntegerField()),
                ('period_name', models.CharField(max_length=100)),
                ('terms', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_subscription', models.BooleanField(default=False)),
                ('customer_order_id', models.BigIntegerField()),
                ('payment_type', models.CharField(choices=[('C', 'Cash on Delivery'), ('N', 'Net Banking'), ('U', 'UPI'), ('D', 'Debit/Credit Cards')], default='C', max_length=1)),
                ('payment_status', models.BooleanField(default=False)),
                ('shipping_status', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.CharField(max_length=1000)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('avail_quantity', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=5000)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('users_rated', models.IntegerField(default=0)),
                ('is_combo', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('category_ids', models.ManyToManyField(to='products.Categories')),
                ('combo_product_ids', models.ManyToManyField(through='products.Combo', to='products.Products')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('A', 'ACTIVE'), ('P', 'PAUSED'), ('C', 'CANCELLED'), ('F', 'FINISHED')], default='A', max_length=1)),
                ('next_order_date', models.DateTimeField()),
                ('last_order_date', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Categories')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Orders')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='combo',
            name='combo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='combo_combo_id', to='products.Products'),
        ),
        migrations.AddField(
            model_name='combo',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_product_id', to='products.Products'),
        ),
        migrations.AddField(
            model_name='cartproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Products'),
        ),
        migrations.AddField(
            model_name='cartproducts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
