# Generated by Django 2.0.2 on 2018-02-20 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='paid_till',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartproducts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='combo',
            name='combo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_combo_id', to='products.Products'),
        ),
        migrations.AlterField(
            model_name='combo',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity', to='products.Products'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment_type',
            field=models.CharField(choices=[('C', 'CASH ON DELIVERY'), ('N', 'NET BANKING'), ('U', 'UPI'), ('D', 'DEBIT/CREDIT CARDS')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='status',
            field=models.CharField(choices=[('A', 'ACTIVE'), ('P', 'PAUSED'), ('C', 'CANCELLED'), ('F', 'FINISHED'), ('I', 'INACTIVE')], default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
