# Generated by Django 2.0.2 on 2018-02-13 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='isSubscription',
            new_name='is_subscription',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='CategoryIDs',
            new_name='category_ids',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='ComboProductIDs',
            new_name='combo_product_ids',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='isCombo',
            new_name='is_combo',
        ),
        migrations.AlterField(
            model_name='cartproducts',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
