# Generated by Django 2.0.2 on 2018-02-13 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180213_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproducts',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='products',
            name='combo_product_ids',
            field=models.ManyToManyField(related_name='_products_combo_product_ids_+', to='products.Products'),
        ),
    ]
