# Generated by Django 2.0.2 on 2018-02-21 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180221_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproducts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='last_order_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='next_order_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='order',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.Orders'),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='start_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
