# Generated by Django 2.0.2 on 2018-02-13 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180213_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproducts',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='cartproducts',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='subscriptions',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='subscriptions',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='subscriptions',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='subscriptions',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='cartproducts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
