# Generated by Django 2.0.2 on 2018-02-23 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20180223_1457'),
        ('products', '0011_auto_20180223_1507'),
    ]

    operations = [
    ]
