# Generated by Django 2.0.2 on 2018-02-27 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20180227_1812'),
        ('products', '0014_auto_20180226_1808'),
    ]

    operations = [
    ]
