# Generated by Django 2.0.2 on 2018-03-02 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_merge_20180227_2044'),
        ('products', '0015_auto_20180228_1538'),
    ]

    operations = [
    ]
